"""push

Revision ID: 52a804dcd232
Revises: 
Create Date: 2026-04-04 05:07:40.807341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a804dcd232'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_formula_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('formula_text', sa.String(length=260), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('level_growth_value', sa.Float(), nullable=False),
    sa.Column('coefficient_a', sa.Float(), nullable=False),
    sa.Column('coefficient_b', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=260), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key')
    )
    op.create_table('currency_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('currency_kind', sa.String(length=40), nullable=False),
    sa.Column('acquisition_rule', sa.String(length=260), nullable=False),
    sa.Column('spend_rule', sa.String(length=260), nullable=False),
    sa.Column('base_unit_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('game_world_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('world_name', sa.String(length=120), nullable=False),
    sa.Column('art_style', sa.String(length=200), nullable=False),
    sa.Column('primary_boss_name', sa.String(length=120), nullable=False),
    sa.Column('secondary_boss_name', sa.String(length=120), nullable=False),
    sa.Column('multiplayer_mode', sa.String(length=80), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('target_level_one_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_bracket_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_level', sa.Integer(), nullable=False),
    sa.Column('end_level', sa.Integer(), nullable=False),
    sa.Column('exp_per_level', sa.Integer(), nullable=False),
    sa.Column('total_exp_for_bracket', sa.Integer(), nullable=False),
    sa.Column('growth_label', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('rarity', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_key', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=260), nullable=False),
    sa.Column('auto_growth_per_level', sa.Integer(), nullable=False),
    sa.Column('allows_teacher_bonus', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_neon_user_id'), 'users', ['neon_user_id'], unique=True)
    op.create_table('activity_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.Column('icon_emoji', sa.String(length=16), nullable=False),
    sa.Column('price_gold', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_plan', sa.String(length=260), nullable=True),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=True),
    sa.Column('public_url', sa.String(length=600), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raid_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('boss_name', sa.String(length=120), nullable=False),
    sa.Column('boss_max_hp', sa.Integer(), nullable=False),
    sa.Column('boss_current_hp', sa.Integer(), nullable=False),
    sa.Column('class_max_hp', sa.Integer(), nullable=False),
    sa.Column('class_current_hp', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('access_code', sa.String(length=24), nullable=False),
    sa.Column('character_class', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grade_tier', sa.String(length=40), nullable=False),
    sa.Column('badge_tier', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('class_points', sa.Integer(), nullable=False),
    sa.Column('attack_power', sa.Integer(), nullable=False),
    sa.Column('defense_power', sa.Integer(), nullable=False),
    sa.Column('support_power', sa.Integer(), nullable=False),
    sa.Column('total_exp', sa.Integer(), nullable=False),
    sa.Column('won_balance', sa.Integer(), nullable=False),
    sa.Column('nyang_balance', sa.Integer(), nullable=False),
    sa.Column('core_balance', sa.Integer(), nullable=False),
    sa.Column('starlight_shard_balance', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('creativity', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Integer(), nullable=False),
    sa.Column('vitality', sa.Integer(), nullable=False),
    sa.Column('diligence', sa.Integer(), nullable=False),
    sa.Column('communication', sa.Integer(), nullable=False),
    sa.Column('bonus_stat_points', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_crit_rate', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_access_code'), 'students', ['access_code'], unique=True)
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=False)
    op.create_table('activity_coupon_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price_gold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['activity_coupons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_coupon_purchases_coupon_id'), 'activity_coupon_purchases', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_activity_coupon_purchases_student_id'), 'activity_coupon_purchases', ['student_id'], unique=False)
    op.create_table('activity_coupon_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['activity_coupons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_coupon_usages_coupon_id'), 'activity_coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_activity_coupon_usages_student_id'), 'activity_coupon_usages', ['student_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_student_id'), 'bank_transactions', ['student_id'], unique=False)
    op.create_table('card_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('issuer_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('stat_delta', sa.Integer(), nullable=False),
    sa.Column('level_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_events_student_id'), 'card_events', ['student_id'], unique=False)
    op.create_table('funding_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['funding_projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_contributions_project_id'), 'funding_contributions', ['project_id'], unique=False)
    op.create_index(op.f('ix_funding_contributions_student_id'), 'funding_contributions', ['student_id'], unique=False)
    op.create_table('question_bank_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('unit_name', sa.String(length=120), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('bonus_attack', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['question_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_items_source_file_id'), 'question_bank_items', ['source_file_id'], unique=False)
    op.create_table('raid_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('healing', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raid_session_id'], ['raid_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_action_logs_raid_session_id'), 'raid_action_logs', ['raid_session_id'], unique=False)
    op.create_table('shop_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_purchases_item_id'), 'shop_purchases', ['item_id'], unique=False)
    op.create_index(op.f('ix_shop_purchases_student_id'), 'shop_purchases', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_purchases_student_id'), table_name='shop_purchases')
    op.drop_index(op.f('ix_shop_purchases_item_id'), table_name='shop_purchases')
    op.drop_table('shop_purchases')
    op.drop_index(op.f('ix_raid_action_logs_raid_session_id'), table_name='raid_action_logs')
    op.drop_table('raid_action_logs')
    op.drop_index(op.f('ix_question_bank_items_source_file_id'), table_name='question_bank_items')
    op.drop_table('question_bank_items')
    op.drop_index(op.f('ix_funding_contributions_student_id'), table_name='funding_contributions')
    op.drop_index(op.f('ix_funding_contributions_project_id'), table_name='funding_contributions')
    op.drop_table('funding_contributions')
    op.drop_index(op.f('ix_card_events_student_id'), table_name='card_events')
    op.drop_table('card_events')
    op.drop_index(op.f('ix_bank_transactions_student_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_activity_coupon_usages_student_id'), table_name='activity_coupon_usages')
    op.drop_index(op.f('ix_activity_coupon_usages_coupon_id'), table_name='activity_coupon_usages')
    op.drop_table('activity_coupon_usages')
    op.drop_index(op.f('ix_activity_coupon_purchases_student_id'), table_name='activity_coupon_purchases')
    op.drop_index(op.f('ix_activity_coupon_purchases_coupon_id'), table_name='activity_coupon_purchases')
    op.drop_table('activity_coupon_purchases')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_index(op.f('ix_students_access_code'), table_name='students')
    op.drop_table('students')
    op.drop_table('raid_sessions')
    op.drop_table('question_files')
    op.drop_table('funding_projects')
    op.drop_table('activity_coupons')
    op.drop_index(op.f('ix_users_neon_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('stat_definitions')
    op.drop_table('shop_items')
    op.drop_table('level_bracket_rules')
    op.drop_table('game_world_settings')
    op.drop_table('currency_rules')
    op.drop_table('combat_formula_rules')
    # ### end Alembic commands ###
