"""push

Revision ID: 52a804dcd232
Revises:
Create Date: 2026-04-05 16:35:04.183053

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52a804dcd232'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Baseline migration is intentionally a no-op.

    The template database can already include baseline tables in this environment.
    Keeping this revision as no-op prevents duplicate-table failures and allows
    subsequent autogenerated revisions to apply incremental changes safely.
    """
    pass


def downgrade() -> None:
    """No-op downgrade for baseline revision."""
    pass
